language: node_js
node_js:
  - stable
before_script:
  - npm install -g typescript@1.0
install:
  - npm install
script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"