language: node_js
services: mongodb  
cache:  
  directories:
    - "node_modules"
  yarn: true
node_js:
  - stable
before_script:
  - npm install -g typescript
install:
  - npm install
script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"