language: node_js
node_js:
  - stable
services: < — — — — — -This was the soultion
  – mongodb
install:
  - npm upgrade && install
script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"